sudo: required
services: docker
install:
- bundle install
script:
- bundle exec kitchen test
notifications:
  slack:
    secure: KIn9urvZ0xm+vMh1GRCmqTd8OvRMTKF0spP2uHIfCpvIzctW/pzyRxz9GH2ORU6rf9nEySji+qn/fQ27VtTImMxa+H0iUuDDWtJ6osUKZGpDxVHnSG4IrTe4SzpPNvJ0Mv8XwpfH1WWmPsbKUBJz5boYJ2dfOeGeJZ/rDbuQgvXjD9kkHE/95bdetSpSMia5vyacdhE09W+qDWksKWd8JyG9YXblQu0UtKUnJUTBzSVY+NUQnxx+XoL8x4eDa1coYRXtJa6Va/5FGk5M2NXXRtyjtbKnMIee2qqdVqALKi98a6xn29Akg5Li1t7Omej6J0PRcOKIrTgHpPy6nSJzlMD0TV1wydHphuu1qT+1hHUjx/+Uc0e4S6RLTw8o9oc0G2KAJu2utLQyRagIigkJcewE7RfqXV0M2BksR+0znZF0hh98mf4kYZmU3LKf+29ysoW7wgQC0bAQliPA/xnhdqrPF1DEDEFcA514f7cPXE9cDU2N7KWZM7J+OmLMawXTR29jYYYSPKtDxB6yZoTYk/O019ACOcfH4Wxk5vYGHhTorZ6+aG9wn+ocTF/3nIfqGLxjd6z0rZfvnbEcpzH2FFLe3x2ULucFvYBJ47ZQo5v4lYsWChwtcZaXCk4QNnP/I74YHpk5gOzJw1mhZyRU6oU7ByAWXOQT/s43d2acT1c=
