---
- name: Upload Config | squid
  template:
    src: "{{ item }}"
    dest: "/{{ item }}"
  with_items:
    - etc/squid3/squid.conf
  tags:
    - configuration
    - template-configuration
    - squid
