---
- name: "Directory Exists | {{ squid_runtime_root }}"
  file:
    state: directory
    path: "{{ squid_runtime_root }}"
    owner: "{{ squid_user }}"
    group: wcadmin
    mode: 0775
  tags:
    - directory-structure
    - runtime-data
    - squid

- name: Upload Config | squid
  template:
    src: "{{ item }}"
    dest: "/{{ item }}"
  with_items:
    - etc/squid3/squid.conf
  tags:
    - configuration
    - template-configuration
    - squid
